spring.application.name=api-gateway

spring.profiles.active=dev

spring.config.import=optional:configserver:http://${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}

spring.cloud.config.fail-fast=true

spring.cloud.gateway.server.webflux.routes[0].id=user_route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-microservice
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/usr/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/api/usr(?<segment>/?.*), /user${segment}

spring.cloud.gateway.server.webflux.routes[1].id=job_route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://job-microservice
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/job/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/api/job(?<segment>/?.*), /job${segment}
