server:
  port: 9000
  
# Gateway configuration
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user_route
              uri: http://localhost:9044
              predicates:
              - Path=/api/usr/**
              filters:
              - RewritePath=/api/usr(?<segment>/?.*), /user\${segment}
            - id: user_route_exact
              uri: http://localhost:9044
              predicates:
              - Path=/api/usr
              filters:
              - RewritePath=/api/usr, /user
            - id: job_route
              uri: http://localhost:9055
              predicates:
              - Path=/api/job/**
              filters:
              - RewritePath=/api(?<segment>/?.*), \${segment}
            - id: job_route_exact
              uri: http://localhost:9055
              predicates:
              - Path=/api/job
              filters:
              - RewritePath=/api/job, /job

# Spring Boot Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Application info
info:
  application:
    name: Api Gateway
    description: Openjob Api Gateway
    version: 0.0.1-SNAPSHOT

logging:
  level:
    org.springframework.cloud.gateway: TRACE