# Port of the service
server.port=9092

# Data source configuration 
spring.datasource.url=jdbc:h2:mem:openjob
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Spring JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Actuator configuration
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

# Application info (to be exposed by /info actuator)
info.application.name=Openjob
info.application.description=Openjob monolithic application
info.application.version=0.0.1-SNAPSHOT
