services:
  openjob-mysql:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  openjob-phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    links:
      - "openjob-mysql:db"
    depends_on:
      - openjob-mysql

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"

  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
    environment:
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
    depends_on:
      - config-server

  gateway:
    build: ./gateway
    ports:
      - "9000:9000"
    environment:
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER: http://discovery-server:8761/eureka/
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,refresh,gateway
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_ID: user_route
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_URI: lb://user-microservice
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_PREDICATES_0: Path=/api/usr/**
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_FILTERS_0: RewritePath=/api/usr(?<segment>/?.*), /user$${segment}
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_ID: job_route
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_URI: lb://job-microservice
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_PREDICATES_0: Path=/api/job/**
      SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_1_FILTERS_0: RewritePath=/api/job(?<segment>/?.*), /job$${segment}
    depends_on:
      - config-server
      - discovery-server

  user-microservice:
    build: ./user
    ports:
      - "9044-9049:9044"
    environment:
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER: http://discovery-server:8761/eureka/
      MYSQL_HOST: openjob-mysql:3306
      MYSQL_DB: user
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - config-server
      - discovery-server
      - openjob-mysql

  job-microservice:
    build: ./job
    expose:
      - "9055"
    environment:
      CONFIG_SERVER_HOST: config-server
      CONFIG_SERVER_PORT: 8888
      EUREKA_SERVER: http://discovery-server:8761/eureka/
      MYSQL_HOST: openjob-mysql:3306
      MYSQL_DB: job
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      MICROSERVICE_USER_FIND_URI: http://user-microservice:9044/user/username/
      MICROSERVICE_USER_BASE_URI: http://user-microservice:9044/user/
    depends_on:
      - config-server
      - discovery-server
      - openjob-mysql
      - user-microservice

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway
volumes:
  mysql-data:
